package com.tracer.kiosk.presentation.tracerbot.response

import com.tracer.kiosk.presentation.tracerbot.model.Faculty

/**
 * Represents the final response generated by TracerBot.
 *
 * This object contains everything the UI needs to display
 * the response and any related faculty information.
 *
 * The Response Engine creates this object.
 */
data class TracerBotResponse(

    /**
     * Main response text shown to the user.
     */
    val message: String,

    /**
     * Optional faculty member associated with the response.
     */
    val facultyName: String? = null,

    /**
     * Matching faculty members found during the search.
     *
     * This allows the UI to display alternative matches
     * when more than one faculty member is relevant.
     */
    val facultyMatches: List<Faculty> = emptyList(),

    /**
     * Whether the UI should provide a navigation action.
     */
    val showNavigationAction: Boolean = false,

    /**
     * Optional destination that can be used by the
     * navigation system.
     */
    val navigationDestination: String? = null,

    /**
     * Whether the response contains useful information
     * about a faculty member.
     */
    val hasFacultyInformation: Boolean = false
)